//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESLEntities : DbContext
    {
        public ESLEntities()
            : base("name=ESLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Class> Tbl_Class { get; set; }
        public virtual DbSet<Tbl_ClassPlan> Tbl_ClassPlan { get; set; }
        public virtual DbSet<Tbl_Code> Tbl_Code { get; set; }
        public virtual DbSet<Tbl_CodeGroup> Tbl_CodeGroup { get; set; }
        public virtual DbSet<Tbl_Document> Tbl_Document { get; set; }
        public virtual DbSet<Tbl_ExamInPerson> Tbl_ExamInPerson { get; set; }
        public virtual DbSet<Tbl_ExamInPersonPlan> Tbl_ExamInPersonPlan { get; set; }
        public virtual DbSet<Tbl_ExamRemotelyPlan> Tbl_ExamRemotelyPlan { get; set; }
        public virtual DbSet<Tbl_Gallery> Tbl_Gallery { get; set; }
        public virtual DbSet<Tbl_GalleryDocument> Tbl_GalleryDocument { get; set; }
        public virtual DbSet<Tbl_Menu> Tbl_Menu { get; set; }
        public virtual DbSet<Tbl_Organization> Tbl_Organization { get; set; }
        public virtual DbSet<Tbl_Page> Tbl_Page { get; set; }
        public virtual DbSet<Tbl_PageCategory> Tbl_PageCategory { get; set; }
        public virtual DbSet<Tbl_PageDocuments> Tbl_PageDocuments { get; set; }
        public virtual DbSet<Tbl_PageTags> Tbl_PageTags { get; set; }
        public virtual DbSet<Tbl_Payment> Tbl_Payment { get; set; }
        public virtual DbSet<Tbl_Question> Tbl_Question { get; set; }
        public virtual DbSet<Tbl_Region> Tbl_Region { get; set; }
        public virtual DbSet<Tbl_Response> Tbl_Response { get; set; }
        public virtual DbSet<Tbl_Role> Tbl_Role { get; set; }
        public virtual DbSet<Tbl_SMSProviderConfiguration> Tbl_SMSProviderConfiguration { get; set; }
        public virtual DbSet<Tbl_SMSProviderNumber> Tbl_SMSProviderNumber { get; set; }
        public virtual DbSet<Tbl_SMSResponse> Tbl_SMSResponse { get; set; }
        public virtual DbSet<Tbl_SMSSetting> Tbl_SMSSetting { get; set; }
        public virtual DbSet<Tbl_SMSTemplate> Tbl_SMSTemplate { get; set; }
        public virtual DbSet<Tbl_SubExamInPerson> Tbl_SubExamInPerson { get; set; }
        public virtual DbSet<Tbl_SubMenu> Tbl_SubMenu { get; set; }
        public virtual DbSet<Tbl_SubWorkshop> Tbl_SubWorkshop { get; set; }
        public virtual DbSet<Tbl_Tag> Tbl_Tag { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
        public virtual DbSet<Tbl_UserClassPlan> Tbl_UserClassPlan { get; set; }
        public virtual DbSet<Tbl_UserClassPlanPresence> Tbl_UserClassPlanPresence { get; set; }
        public virtual DbSet<Tbl_UserExamInPersonPlan> Tbl_UserExamInPersonPlan { get; set; }
        public virtual DbSet<Tbl_UserExamRemotelyPlan> Tbl_UserExamRemotelyPlan { get; set; }
        public virtual DbSet<Tbl_UserExamRemotelyPlanAccess> Tbl_UserExamRemotelyPlanAccess { get; set; }
        public virtual DbSet<Tbl_UserWorkshopPlan> Tbl_UserWorkshopPlan { get; set; }
        public virtual DbSet<Tbl_Wallet> Tbl_Wallet { get; set; }
        public virtual DbSet<Tbl_Workshop> Tbl_Workshop { get; set; }
        public virtual DbSet<Tbl_WorkshopPlan> Tbl_WorkshopPlan { get; set; }
    }
}
