//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Wallet
    {
        public int Wallet_ID { get; set; }
        public System.Guid Wallet_Guid { get; set; }
        public int Wallet_UserID { get; set; }
        public int Wallet_Credit { get; set; }
        public System.DateTime Wallet_CreationDate { get; set; }
        public System.DateTime Wallet_ModifiedDate { get; set; }
        public bool Wallet_IsDelete { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
