//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UserExamInPersonPlan
    {
        public int UEIPP_ID { get; set; }
        public System.Guid UEIPP_Guid { get; set; }
        public int UEIPP_UserID { get; set; }
        public int UEIPP_EIPPID { get; set; }
        public int UEIPP_SeatNumber { get; set; }
        public int UEIPP_Mark { get; set; }
        public Nullable<int> UEIPP_PaymentID { get; set; }
        public bool UEIPP_IsPresent { get; set; }
        public bool UEIPP_IsActive { get; set; }
        public System.DateTime UEIPP_CreationDate { get; set; }
        public System.DateTime UEIPP_ModifiedDate { get; set; }
        public bool UEIPP_IsDelete { get; set; }
    
        public virtual Tbl_ExamInPersonPlan Tbl_ExamInPersonPlan { get; set; }
        public virtual Tbl_Payment Tbl_Payment { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
