//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Organization
    {
        public int Organization_ID { get; set; }
        public System.Guid Organization_Guid { get; set; }
        public int Organization_DocumentID { get; set; }
        public int Organization_TypeCodeID { get; set; }
        public string Organization_URL { get; set; }
        public bool Organization_IsDelete { get; set; }
    
        public virtual Tbl_Code Tbl_Code { get; set; }
        public virtual Tbl_Document Tbl_Document { get; set; }
    }
}
