//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Question()
        {
            this.Tbl_Response1 = new HashSet<Tbl_Response>();
        }
    
        public int Question_ID { get; set; }
        public System.Guid Question_Guid { get; set; }
        public int Question_ERID { get; set; }
        public int Question_GroupCodeID { get; set; }
        public Nullable<int> Question_ResponseID { get; set; }
        public int Question_TypeCodeID { get; set; }
        public string Question_Title { get; set; }
        public int Question_Mark { get; set; }
        public int Question_Order { get; set; }
        public System.DateTime Question_CreationDate { get; set; }
        public System.DateTime Question_ModifiedDate { get; set; }
        public bool Question_IsDelete { get; set; }
    
        public virtual Tbl_Code Tbl_Code { get; set; }
        public virtual Tbl_Code Tbl_Code1 { get; set; }
        public virtual Tbl_ExamRemotelyPlan Tbl_ExamRemotelyPlan { get; set; }
        public virtual Tbl_Response Tbl_Response { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Response> Tbl_Response1 { get; set; }
    }
}
