//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Menu()
        {
            this.Tbl_SubMenu = new HashSet<Tbl_SubMenu>();
        }
    
        public int Menu_ID { get; set; }
        public System.Guid Menu_Guid { get; set; }
        public string Menu_Name { get; set; }
        public string Menu_Display { get; set; }
        public int Menu_Order { get; set; }
        public bool Menu_HasSubMenu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SubMenu> Tbl_SubMenu { get; set; }
    }
}
