//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Payment()
        {
            this.Tbl_UserClassPlanPresence = new HashSet<Tbl_UserClassPlanPresence>();
            this.Tbl_UserClassPlan = new HashSet<Tbl_UserClassPlan>();
            this.Tbl_UserExamInPersonPlan = new HashSet<Tbl_UserExamInPersonPlan>();
            this.Tbl_UserWorkshopPlan = new HashSet<Tbl_UserWorkshopPlan>();
        }
    
        public int Payment_ID { get; set; }
        public System.Guid Payment_Guid { get; set; }
        public int Payment_UserID { get; set; }
        public int Payment_TitleCodeID { get; set; }
        public Nullable<int> Payment_WayCodeID { get; set; }
        public int Payment_StateCodeID { get; set; }
        public string Payment_Description { get; set; }
        public int Payment_Cost { get; set; }
        public int Payment_Discount { get; set; }
        public int Payment_RemaingWallet { get; set; }
        public string Payment_TrackingToken { get; set; }
        public Nullable<int> Payment_DocumentID { get; set; }
        public System.DateTime Payment_CreateDate { get; set; }
        public System.DateTime Payment_ModifiedDate { get; set; }
        public bool Payment_IsDelete { get; set; }
    
        public virtual Tbl_Code Tbl_Code { get; set; }
        public virtual Tbl_Code Tbl_Code1 { get; set; }
        public virtual Tbl_Code Tbl_Code2 { get; set; }
        public virtual Tbl_Document Tbl_Document { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UserClassPlanPresence> Tbl_UserClassPlanPresence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UserClassPlan> Tbl_UserClassPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UserExamInPersonPlan> Tbl_UserExamInPersonPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UserWorkshopPlan> Tbl_UserWorkshopPlan { get; set; }
    }
}
