//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Page
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Page()
        {
            this.Tbl_PageDocuments = new HashSet<Tbl_PageDocuments>();
            this.Tbl_PageTags = new HashSet<Tbl_PageTags>();
        }
    
        public int Page_ID { get; set; }
        public System.Guid Page_Guid { get; set; }
        public int Page_UserID { get; set; }
        public int Page_RegionID { get; set; }
        public int Page_PCID { get; set; }
        public string Page_Titel { get; set; }
        public string Page_Description { get; set; }
        public int Page_IsDelete { get; set; }
        public System.DateTime Page_CreateDate { get; set; }
        public System.DateTime Page_Modify { get; set; }
        public string Page_Abstract { get; set; }
    
        public virtual Tbl_PageCategory Tbl_PageCategory { get; set; }
        public virtual Tbl_Region Tbl_Region { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PageDocuments> Tbl_PageDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PageTags> Tbl_PageTags { get; set; }
    }
}
