//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SMSSetting
    {
        public int SS_ID { get; set; }
        public System.Guid SS_Guid { get; set; }
        public int SS_SPCID { get; set; }
        public int SS_STID { get; set; }
        public System.DateTime SS_CreationDate { get; set; }
        public System.DateTime SS_ModifiedDate { get; set; }
        public bool SS_IsDelete { get; set; }
    
        public virtual Tbl_SMSProviderConfiguration Tbl_SMSProviderConfiguration { get; set; }
        public virtual Tbl_SMSTemplate Tbl_SMSTemplate { get; set; }
    }
}
