//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SMSResponse
    {
        public int SMS_ID { get; set; }
        public System.Guid SMS_Guid { get; set; }
        public int SMS_Status { get; set; }
        public string SMS_StatusText { get; set; }
        public string SMS_MessageID { get; set; }
        public string SMS_Message { get; set; }
        public string SMS_Token { get; set; }
        public string SMS_Token1 { get; set; }
        public string SMS_Token2 { get; set; }
        public string SMS_Sender { get; set; }
        public string SMS_Receptor { get; set; }
        public System.DateTime SMS_Date { get; set; }
        public int SMS_Cost { get; set; }
        public System.DateTime SMS_CreationDate { get; set; }
        public System.DateTime SMS_ModifiedDate { get; set; }
        public bool SMS_IsDelete { get; set; }
    }
}
