//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ClassPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_ClassPlan()
        {
            this.Tbl_UserClassPlan = new HashSet<Tbl_UserClassPlan>();
        }
    
        public int CP_ID { get; set; }
        public System.Guid CP_Guid { get; set; }
        public int CP_ClassID { get; set; }
        public int CP_TypeCodeID { get; set; }
        public int CP_Capacity { get; set; }
        public string CP_Description { get; set; }
        public int CP_CostPerSession { get; set; }
        public string CP_Location { get; set; }
        public System.TimeSpan CP_Time { get; set; }
        public double CP_SessionsLength { get; set; }
        public System.DateTime CP_StartDate { get; set; }
        public bool CP_IsActive { get; set; }
        public System.DateTime CP_CreationDate { get; set; }
        public System.DateTime CP_ModifiedDate { get; set; }
        public bool CP_IsDelete { get; set; }
    
        public virtual Tbl_Class Tbl_Class { get; set; }
        public virtual Tbl_Code Tbl_Code { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UserClassPlan> Tbl_UserClassPlan { get; set; }
    }
}
