//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Workshop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Workshop()
        {
            this.Tbl_SubWorkshop = new HashSet<Tbl_SubWorkshop>();
        }
    
        public int Workshop_ID { get; set; }
        public System.Guid Workshop_Guid { get; set; }
        public string Workshop_Title { get; set; }
        public bool Workshop_HasSubWorkshop { get; set; }
        public System.DateTime Workshop_CreationDate { get; set; }
        public System.DateTime Workshop_ModifiedDate { get; set; }
        public bool Workshop_IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SubWorkshop> Tbl_SubWorkshop { get; set; }
    }
}
