//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SubMenu
    {
        public int SM_ID { get; set; }
        public System.Guid SM_Guid { get; set; }
        public int SM_MenuID { get; set; }
        public string SM_Name { get; set; }
        public string SM_Display { get; set; }
        public int SM_Order { get; set; }
    
        public virtual Tbl_Menu Tbl_Menu { get; set; }
    }
}
