//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SMSTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_SMSTemplate()
        {
            this.Tbl_SMSSetting = new HashSet<Tbl_SMSSetting>();
        }
    
        public int ST_ID { get; set; }
        public System.Guid ST_Guid { get; set; }
        public string ST_Name { get; set; }
        public System.DateTime ST_CreationDate { get; set; }
        public System.DateTime ST_ModifiedDate { get; set; }
        public bool ST_IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SMSSetting> Tbl_SMSSetting { get; set; }
    }
}
