//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_WorkshopPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_WorkshopPlan()
        {
            this.Tbl_UserWorkshopPlan = new HashSet<Tbl_UserWorkshopPlan>();
        }
    
        public int WP_ID { get; set; }
        public System.Guid WP_Guid { get; set; }
        public int WP_SWID { get; set; }
        public int WP_Capacity { get; set; }
        public string WP_Description { get; set; }
        public int WP_Cost { get; set; }
        public string WP_Location { get; set; }
        public System.DateTime WP_Date { get; set; }
        public bool WP_IsActive { get; set; }
        public System.DateTime WP_CreationDate { get; set; }
        public System.DateTime WP_ModifiedDate { get; set; }
        public bool WP_IsDelete { get; set; }
    
        public virtual Tbl_SubWorkshop Tbl_SubWorkshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UserWorkshopPlan> Tbl_UserWorkshopPlan { get; set; }
    }
}
