//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UserWorkshopPlan
    {
        public int UWP_ID { get; set; }
        public System.Guid UWP_Guid { get; set; }
        public int UWP_UserID { get; set; }
        public int UWP_WPID { get; set; }
        public Nullable<int> UWP_PaymentID { get; set; }
        public bool UWP_IsPresent { get; set; }
        public bool UWP_IsActive { get; set; }
        public System.DateTime UWP_CreationDate { get; set; }
        public System.DateTime UWP_ModifiedDate { get; set; }
        public bool UWP_IsDelete { get; set; }
    
        public virtual Tbl_Payment Tbl_Payment { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
        public virtual Tbl_WorkshopPlan Tbl_WorkshopPlan { get; set; }
    }
}
