//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SubWorkshop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_SubWorkshop()
        {
            this.Tbl_WorkshopPlan = new HashSet<Tbl_WorkshopPlan>();
        }
    
        public int SW_ID { get; set; }
        public System.Guid SW_Guid { get; set; }
        public int SW_WorkshopID { get; set; }
        public string SW_Title { get; set; }
        public System.DateTime SW_CreationDate { get; set; }
        public System.DateTime SW_ModifiedDate { get; set; }
        public bool SW_IsDelete { get; set; }
    
        public virtual Tbl_Workshop Tbl_Workshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_WorkshopPlan> Tbl_WorkshopPlan { get; set; }
    }
}
